export const SET_PLAYER = "PLAYER/SET_PLAYER"
export const SET_CURRENTINDEX = "PLAYER/SET_CURRENTINDEX"
export const SET_PLAYINGTRACK = "PLAYER/SET_PLAYINGTRACK"
export const SET_QUEUE = "PLAYER/SET_QUEUE"